### ISSUE TITLE
Enable a GenAIScript to be packaged as a JavaScript/TypeScript function

### ISSUE THREAD

**Issue by bzorn** [microsoft/genaiscript#450]
Currently input and output of GenAIScript is via creating files, etc.  We could support the ability to have a wrapper for a script that would use a TypeScript signature to define the inputs and outputs and allow the script to be called as a normal function within other JavaScript/TypeScript code.

**Comment by tballmsft** [comment]
basically, I want an in-memory way to call genaiscript.  I want to supply a function type signature to genai that tells it the input types (rather than input files) and output type (rather than a file/files). I also supply a "function body" that uses genaiscript to implement the body, referring to the typed input params. genaiscript provides all the plumbing to convert from (typed) input values into prompt, and back out again.

Not clear what this actually looks like in code, yet.

**Comment by pelikhan** [comment]
Do you have a sketch of your idea? Is this function meant to be called by another script or is it still a GenAI.js script?
________________________________

**Comment by pelikhan** [comment]
Note that scripts can have typed parameters so we already have parts of what you want.

https://microsoft.github.io/genaiscript/reference/scripts/variables/#script-parameters

**Comment by pelikhan** [comment]
one solution would be to drop a .ts file (or .py) that wraps a call to the CLI using the parameters and returning the full output. might be overkill

**Comment by pelikhan** [comment]
tracking in https://github.com/microsoft/genaiscript/issues/450

**Comment by pelikhan** [comment]
see https://github.com/microsoft/genaiscript/pull/925
