### ISSUE TITLE
def FILES is empty

### ISSUE THREAD

**Issue by JSchermers** [microsoft/genaiscript#832]
Hello,

i'm trying to run de markdown example from the docs but i always get an Error.  

![Image](https://github.com/user-attachments/assets/c4949e5e-ff1b-4300-9692-c0aa86233eb8)

this is the trace
![Image](https://github.com/user-attachments/assets/b61f0b4b-a3cd-43de-a605-0f8c80c6e513)

this the genaiscript .mjs
![Image](https://github.com/user-attachments/assets/31853eff-98eb-47c8-b1d9-21ab58ae3be4)

When i don't do 

```
def("File", env.files)
```

but only

```
$`Summarize ${env.files}`
```

from the genaiscript.mjs

i get this

![Image](https://github.com/user-attachments/assets/9b9b16aa-46d3-403d-990f-7b2181666016)

Can anybody explain what this is and maybe how to solve it or what's going wrong? 

Tnx in advance, Joost

**Comment by pelikhan** [comment]
So the def FILES is empty means that `env.files` was somewhat empty, which is very strange because the report indicates that env.files has at least 1 element (can you add a `console.log(env.files)` call before `def("FILES"...)`).

When we render `$Summarize ${env.files}` , we automatically extract the `env.files` variable and place it into a `def("FILES"` promptdom node, with the `ignoreEmpty` option set to true (so that one does not throw.

Could you try modifying the sample to:

```js
console.log(env.files)
const files = def("FILES", env.files, { ignoreEmpty: true })
$`Summarize ${files}.`
```

If you scroll down in the report, in the chat section, you should see the final prompt as sent to the LLM. The LLM is probably complaining because the prompt is asking to summarize files but there are not files.

**Comment by pelikhan** [comment]
Note that all file paths are relative to the workspace root.

**Comment by JSchermers** [comment]
Tnx , that worked. The path of the markdown was wrong. 

It now works as the tutorial describes.

![Image](https://github.com/user-attachments/assets/66252b26-1e3b-48ee-aa68-63156856bd6c)

**Comment by pelikhan** [comment]
I'm going to keep this one opened to improve the error message. In your sample, you can do this instead to avoid duplicating the FILES node:

```js
def("FILES", env.files)
$`Summarize FILES`
```

**Comment by pelikhan** [comment]
Comment added.
