### ISSUE TITLE
Issue installing genaiscript behind a proxy

### ISSUE THREAD

**Issue by sahuguet** [microsoft/genaiscript#853]
I cannot run `npm install genaiscript` behind my enterprise proxy.
The install chokes when trying do download a zip file for the ripgrep package.

```
npm error VError: Failed to download "https://github.com/microsoft/ripgrep-prebuilt/releases/download/v13.0.0-10/ripgrep-v13.0.0-10-x86_64-pc-windows-msvc.zip": RequestError: connect ETIMEDOUT [140.82.112.3:443](http://140.82.112.3:443/)
```

It seems that a lot of JS library have very poor support for proxies.

RipGrep is using `got` instead of the nodeJS built-in ones. See https://github.com/lvce-editor/ripgrep/blob/main/src/downloadRipGrep.js#L67

1. Has anyone experienced similar issue when installing genaiscript?
3. Any easy workaround? Can I comment the package? Another option would be to rewrite the RipGrep code to use `node-fetch` instead of got.

**Comment by pelikhan** [comment]
I've made ripgrep a optionalDependency (https://docs.npmjs.com/cli/v10/configuring-npm/package-json#optionaldependencies) so that, at least the install does not just fail.

(The whole node.js npm ecosystem is a esoteric mix of `fetch` replacement and it'll take a while for all the project to align on the built-in `fetch` api...)

**Comment by pelikhan** [comment]
You can definitely comment this package; it is only used for the grep file search and loaded dynamically.

**Comment by sahuguet** [comment]
Works.
